import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.0'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.openapi.generator' version '7.5.0'
}

group = 'com.bitkulcha'
version = '0.0.1-SNAPSHOT'
description = 'Notification engine'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-liquibase'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
	implementation 'org.springframework.integration:spring-integration-mqtt:6.2.0'
	implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
	implementation 'com.github.f4b6a3:uuid-creator:6.0.0'
	implementation 'io.swagger.core.v3:swagger-annotations:2.2.15'
	implementation 'io.swagger.core.v3:swagger-models:2.2.15'
	implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
	implementation 'org.hibernate.validator:hibernate-validator:8.0.1.Final'
	implementation 'org.openapitools:jackson-databind-nullable:0.2.11'
	implementation 'com.google.firebase:firebase-admin:9.10.0'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-data-jpa-test'
	testImplementation 'org.springframework.security:spring-security-test'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
	runtimeOnly 'com.h2database:h2'

	compileOnly 'org.immutables:value:2.10.1'
	annotationProcessor 'org.immutables:value:2.10.1'
	compileOnly 'org.projectlombok:lombok:1.18.46'
	annotationProcessor 'org.projectlombok:lombok:1.18.46'
	testCompileOnly 'org.projectlombok:lombok:1.18.46'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.46'
}

def swaggerDir = file("$rootDir/src/main/resources/swagger")
File[] apiSpecs = swaggerDir.listFiles({ f -> f.name.endsWith(".yaml") } as FileFilter)
apiSpecs.each { spec ->
	tasks.register("${spec.name.replaceFirst(/\.yaml$/, "").capitalize()}ApiGenerate", GenerateTask) {
		generatorName = "spring"
		inputSpec = spec.absolutePath
		outputDir = "$rootDir/build/generated/"
		apiPackage = "com.bitkulcha.notification_engine.api"
		modelPackage = "com.bitkulcha.notification_engine.model"
		configOptions = [
				interfaceOnly: "true",
				skipDefaultInterface: "true",
				useJakartaEe: "true"
		]
	}
}

tasks.register("openApiGenerateAll") {
	dependsOn apiSpecs.collect { "${it.name.replaceFirst(/\.yaml$/, "").capitalize()}ApiGenerate" }
}

sourceSets {
	main {
		java {
			srcDir "$rootDir/build/generated/src/main/java"
		}
	}
}

bootJar {
	archiveFileName = "app.jar"
}

//tasks.register('stage') {
//	dependsOn['bootJar']
//}

tasks.bootJar {
	archiveClassifier.set("boot")
}

tasks.jar {
	archiveClassifier.set("")
}

tasks.named('test') {
	useJUnitPlatform()
}

compileJava.dependsOn tasks.openApiGenerateAll