server:
  servlet:
    context-path: /api

logging:
  level:
    com:
      bitkulcha:
        notification_engine: ${LOG_LEVEL:INFO}

spring:
  application:
    name: notification-engine
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

firebase:
  credential: ${FIREBASE_CREDENTIAL}

mqtt:
  broker-id: ${BROKER_ID}